name: Fetch 7shifts sales

on:
  workflow_dispatch:
    inputs:
      week:
        description: "Week-of Monday (YYYY-MM-DD). Leave blank for current week."
        required: false
      companyId:
        description: "7shifts Company ID"
        required: false
        default: "283376"
      locationId:
        description: "7shifts Location ID"
        required: false
        default: "351442"
  schedule:
    # Runs 6am & 6pm Toronto time during DST (10:00/22:00 UTC). 
    # In winter this will be 11:00/23:00 UTC — change later if you want exact local times year-round.
    - cron: "0 10 * * *"
    - cron: "0 22 * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Install deps (noop if package.json doesn't exist)
      - name: Install dependencies
        run: |
          npm -v || true
          npm i firebase-admin node-fetch@3

      - name: Run fetcher
        env:
          SEVENSHIFTS_TOKEN: ${{ secrets.SEVENSHIFTS_TOKEN }}
          FIREBASE_SA_JSON: ${{ secrets.FIREBASE_SA_JSON }}
          COMPANY_ID:  ${{ github.event.inputs.companyId || '283376' }}
          LOCATION_ID: ${{ github.event.inputs.locationId || '351442' }}
          WEEK_OF:     ${{ github.event.inputs.week || '' }}
          WORKSPACE:   tulia
        run: node scripts/fetch_sales.js
