name: Pull 7shifts sales into Firestore

on:
  workflow_dispatch:
    inputs:
      week_of:
        description: 'ISO Monday for the week (YYYY-MM-DD). Leave blank for current week.'
        required: false
  schedule:
    # 6am and 6pm America/Toronto every day
    - cron: '0 6 * * *'
      timezone: America/Toronto
    - cron: '0 18 * * *'
      timezone: America/Toronto

jobs:
  fetch-and-write:
    runs-on: ubuntu-latest
    env:
      WORKSPACE: tulia
      COMPANY_ID: '283376'     # ← your 7shifts company id
      LOCATION_ID: '351442'    # ← your 7shifts location id
      FOOD_PCT_ENABLED: 'false' # just stored alongside for reference (UI controls this)
      FOOD_PCT: '40'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps for script
        run: npm i firebase-admin axios dayjs

      - name: Run script
        env:
          FIREBASE_SA_JSON: ${{ secrets.FIREBASE_SA_JSON }}
          SEVENSHIFTS_TOKEN: ${{ secrets.SEVENSHIFTS_TOKEN }}
          INPUT_WEEK_OF: ${{ github.event.inputs.week_of }}
        run: node scripts/fetch_sales.js
