name: Pull 7shifts sales into Firestore

on:
  workflow_dispatch:
    inputs:
      week_of:
        description: Monday ISO date (YYYY-MM-DD). Leave blank for current Monday.
        required: false
        default: ""
  schedule:
    # 10:00 & 22:00 UTC ≈ 6am & 6pm Toronto during Daylight Time.
    # (If you prefer strict 6/6 year-round we can add a small tz helper later.)
    - cron: "0 10,22 * * *"

jobs:
  fetch-and-write:
    runs-on: ubuntu-latest

    env:
      # Non-secrets you can safely commit here
      WORKSPACE: tulia
      COMPANY_ID: "283376"   # Tulia company id
      LOCATION_ID: "351442"  # Tulia Osteria location id

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm init -y && npm i axios firebase-admin dayjs

      - name: Run fetch script
        env:
          FIREBASE_SA_JSON: ${{ secrets.FIREBASE_SA_JSON }}
          SEVENSHIFTS_TOKEN: ${{ secrets.SEVENSHIFTS_TOKEN }}
        run: |
          node scripts/fetch_7shifts_sales.js \
            --week-of "${{ github.event.inputs.week_of || '' }}" \
            --workspace "$WORKSPACE" \
            --company "$COMPANY_ID" \
            --location "$LOCATION_ID"

