name: fetch-sales

on:
  workflow_dispatch:    # allow manual runs
  schedule:
    # Cron is UTC in GitHub Actions.
    # 6am/6pm Toronto ≈ 10:00 / 22:00 UTC during DST (EDT). In winter (EST) it's 11:00 / 23:00.
    - cron: "0 10,22 * * *"

jobs:
  pull_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-firestore google-auth requests

      - name: Write Firebase service account JSON
        run: |
          echo '${{ secrets.FIREBASE_SA_JSON }}' > $GITHUB_WORKSPACE/sa.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/sa.json" >> $GITHUB_ENV

      - name: Run fetcher
        env:
          SEVENSHIFTS_TOKEN: ${{ secrets.SEVENSHIFTS_TOKEN }}
          COMPANY_ID: "283376"   # <- update if needed
          LOCATION_ID: "351442"  # <- update if needed
          WORKSPACE: "tulia"
          LOCAL_TZ: "America/Toronto"
        run: |
          python scripts/fetch_7shifts_to_firestore.py
